(lang dune 3.24)

(name Double-Pendulum)

(generate_opam_files true)

(source
 (github HBrown06/DoublePendulum))

(authors "Haiden Brown <haidenbrown06@icloud.com>")

(maintainers "Haiden Brown <haidenbrown06@icloud.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name Double-Pendulum)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
